### ISSUE TITLE
[Feat] 피버게이지 프로토타입

### ISSUE THREAD

**Issue by H-SeungWoo** [FavoriteIdol/VirtualIdol#1]
### ISSUE

- Type: Feature
- Detail: 피버게이지

### TODO

- [x] 피버게이지 UI 제작
- [x] 키 입력시 변수 값 조절
- [x] 피버게이지 퍼센트 연동
- [x] 다 채웠을 시 로그 출력
