### ISSUE TITLE
[Feat] 인터뷰 이벤트 구현하기

### ISSUE THREAD

**Issue by H-SeungWoo** [FavoriteIdol/VirtualIdol#19]
### ISSUE

- Type: Feat
- Detail: 인터뷰 구현하기

### TODO

- [x] 인터뷰 시작하기
- [x] 플레이어 선정 (랜덤? 피버게이지 기여?)
- [x] 플레이어 위치 고정시키기
- [x] 카메라 시점 변경하기
- [x] 인터뷰 끝내기

**Comment by H-SeungWoo** [comment]
https://pjnull.tistory.com/98

게임모드에서 유저 추척하기
