### ISSUE TITLE
[Feat] 3D 오브젝트 프로토 디테일

### ISSUE THREAD

**Issue by H-SeungWoo** [FavoriteIdol/VirtualIdol#24]
### ISSUE

- Type: Feat
- Detail: 3D 오브젝트 디테일

### TODO

- [x]  오브젝트 메쉬 바꾸기
- [x]  콜리전되면 일정 시간 후 사라지게하기
- [x]  무대 방향으로 던지게하기

**Comment by H-SeungWoo** [comment]
캐릭터를 항상 무대쪽으로 바라보게 했으나, 공은 카메라가 바라보던 방향과 섞여서 날아가는 현상 발생.
Arrow컴포넌트의 ForwardVector가 원하는대로 나오지 않는 것 같음.

**Comment by H-SeungWoo** [comment]
AddActorLocalRotator와 SetActorRotator의 차이

![image](https://github.com/user-attachments/assets/86563b09-a5a4-4599-bb0b-bf7b06a26c0f)

![image](https://github.com/user-attachments/assets/1cc97b01-f861-4221-8f49-87fbdf25185b)

![image](https://github.com/user-attachments/assets/1da25543-3d4f-473c-b3e0-957640cd0edc)
