### ISSUE TITLE
[Feat] 프로토 무대 준비

### ISSUE THREAD

**Issue by H-SeungWoo** [FavoriteIdol/VirtualIdol#26]
### ISSUE

- Type: Feat
- Detail: 프로토 무대 준비

### TODO

- [x]  캐릭터 컴포넌트, 기능 합치기
- [x]  맵에 공연자, 관객 스폰 세팅
- [x] 맵에 이펙트 위치 설정
- [x] 이펙트 잘 나오게 하기
- [x] 인터뷰 위치 설정
- [x] 음성입력 잘 되는지 확인하기
- [x]  노래 설정하고 재생하기
- [x] 인터뷰 시 마이크 On/Off
- [x] #37

**Comment by H-SeungWoo** [comment]
https://hye-genius.tistory.com/entry/UE4-Runtime-File-Open-C

런타임시 파일탐색기 열기

**Comment by H-SeungWoo** [comment]
런타임시 파일 탐색기를 열어서 음원을 불러오는 것은 안될 듯 함.
![image](https://github.com/user-attachments/assets/5b7d2b59-0525-4b3f-91ea-a55ca6cb0c6d)
