### ISSUE TITLE
[Feat] 이모티콘

### ISSUE THREAD

**Issue by H-SeungWoo** [FavoriteIdol/VirtualIdol#3]
### ISSUE

- Type: Feature
- Detail: 이모티콘 기능

### TODO

- [x]  이모티콘 UI (인벤토리?)
- [x] 이모티콘 컴포넌트 구현
- [x]  버튼클릭 시 해당 이모티콘 연결
- [x] 머리 위에 띄우기
- [x] 일정 시간 이후 없애기
- [x] #12
- [x] 생성될때 폭발? 터지는 이펙트
- [x] 이모티콘 빌보드 처리

**Comment by H-SeungWoo** [comment]
Texture C++로 가져오기
https://forums.unrealengine.com/t/declaring-a-texture-variable/7666/2
h
`
	UPROPERTY ( )
	class UTexture2D* Imoji01Texture;
`

C++
`

static ConstructorHelpers::FObjectFinder<UTexture2D> LoadedImoji01Texture ( TEXT("Texture2D'/Game/Project/Personal/HSW/Resources/Imogi/Imoji_01.Imoji_01'" ) );

	if (LoadedImoji01Texture.Succeeded ( ))
	
	{
	
		Imoji01Texture = LoadedImoji01Texture.Object;
	
	}
	
	else
	
	{
	
		UE_LOG ( LogTemp , Warning , TEXT ( "Failed to load texture Imoji_01" ) );
		
	}
	
`
ConstructorHelpers는 생성자에서 사용해야함

**Comment by H-SeungWoo** [comment]
나이아가라를 사용하기위해서 build.cs에 추가해야함

**Comment by H-SeungWoo** [comment]
https://velog.io/@kjw5912/UE5C-Niagara

**Comment by H-SeungWoo** [comment]
https://dev.epicgames.com/documentation/en-us/unreal-engine/API/Plugins/Niagara/UNiagaraComponent?application_version=4.27

**Comment by H-SeungWoo** [comment]
![image](https://github.com/user-attachments/assets/7cf45d6c-ef99-4b31-9197-e1994204a773)
